// <auto-generated />
using System;
using Inventar.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inventar.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230626213124_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Inventar.Models.Inventari", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Cena")
                        .HasColumnType("int");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ProstorijaId")
                        .HasColumnType("char(36)");

                    b.Property<int>("SerijskiBroj")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProstorijaId");

                    b.ToTable("Inventars");
                });

            modelBuilder.Entity("Inventar.Models.Prostorija", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Duzina")
                        .HasColumnType("int");

                    b.Property<Guid>("IdInventari")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdRadnika")
                        .HasColumnType("char(36)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sef")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Sirina")
                        .HasColumnType("int");

                    b.Property<int>("Sprat")
                        .HasColumnType("int");

                    b.Property<int>("Visina")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Prostorijas");
                });

            modelBuilder.Entity("Inventar.Models.Radnici", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("JMBG")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ProstorijaId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Sprema")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ProstorijaId");

                    b.ToTable("Radnicis");
                });

            modelBuilder.Entity("Inventar.Models.Inventari", b =>
                {
                    b.HasOne("Inventar.Models.Prostorija", null)
                        .WithMany("Inventari")
                        .HasForeignKey("ProstorijaId");
                });

            modelBuilder.Entity("Inventar.Models.Radnici", b =>
                {
                    b.HasOne("Inventar.Models.Prostorija", null)
                        .WithMany("Radnici")
                        .HasForeignKey("ProstorijaId");
                });

            modelBuilder.Entity("Inventar.Models.Prostorija", b =>
                {
                    b.Navigation("Inventari");

                    b.Navigation("Radnici");
                });
#pragma warning restore 612, 618
        }
    }
}
